const catchAsyncError = require("../middlewares/catchAsyncError");

exports.applyForLeave = catchAsyncError(async (req, res) => {
    try {
        
    } catch (err) {
        console.log(err);
    }
});